use tienda; select nombre from producto;
use tienda; select nombre, precio from producto;
use tienda; select * from producto;
use tienda; select nombre, precio, round(precio*1.1,2) as preuDolars from producto;
use tienda; select nombre, precio as Euros, round(precio*1.1,2) as Dolars from producto;
use tienda; select UPPER(nombre), precio from producto;
use tienda; select lower(nombre), precio from producto;
use tienda; select nombre, UPPER(SUBSTR(nombre,1,2)) as nombreMayus from fabricante;
use tienda; select nombre, round(precio,1) from producto;
use tienda; select nombre, floor(precio) from producto;
select fabricante.codigo from tienda.fabricante INNER JOIN tienda.producto ON  fabricante.codigo = producto.codigo_fabricante;
select distinct fabricante.codigo from tienda.fabricante INNER JOIN tienda.producto ON  fabricante.codigo = producto.codigo_fabricante;
select distinct fabricante.codigo from tienda.fabricante INNER JOIN tienda.producto ON  fabricante.codigo = producto.codigo_fabricante;
select distinct fabricante.codigo from tienda.fabricante INNER JOIN tienda.producto ON  fabricante.codigo = producto.codigo_fabricante order by codigo DESC;
use tienda; select nombre, precio from producto order by nombre ASC, precio DESC;
use tienda; select * from fabricante limit 5;
use tienda; select * from fabricante limit 3,2;
use tienda; select nombre, precio from producto order by precio ASC limit 1;
use tienda; select nombre, precio from producto order by precio DESC limit 1;
use tienda; select nombre from producto where codigo_fabricante = 2;
use tienda; select nombre, precio, (select nombre from fabricante where producto.codigo_fabricante = fabricante.codigo) as fabricant from producto;
use tienda; select nombre, precio, (select nombre from fabricante where producto.codigo_fabricante = fabricante.codigo) as fabricant from producto order by fabricant;
use tienda; select codigo, nombre, codigo_fabricante, (select nombre from fabricante where producto.codigo_fabricante = fabricante.codigo) as fabricant from producto;
use tienda; select nombre, precio, (select nombre from fabricante where producto.codigo_fabricante = fabricante.codigo) as fabricant from producto order by precio limit 1;
use tienda; select nombre, precio, (select nombre from fabricante where producto.codigo_fabricante = fabricante.codigo) as fabricant from producto order by precio DESC limit 1;
use tienda; select producto.nombre from producto join fabricante on producto.codigo_fabricante = fabricante.codigo and fabricante.nombre = "Lenovo";
use tienda; select producto.nombre from producto join fabricante on producto.codigo_fabricante = fabricante.codigo and fabricante.nombre = "Crucial" where producto.precio>200;
use tienda; select producto.nombre from producto join fabricante on producto.codigo_fabricante = fabricante.codigo and (fabricante.nombre = "Seagate" or fabricante.nombre = "Asus" or fabricante.nombre = "Hewlett-Packard");
use tienda; select producto.nombre from producto join fabricante on producto.codigo_fabricante = fabricante.codigo and fabricante.nombre in ("Seagate" , "Asus" ,"Hewlett-Packard");
use tienda; select producto.nombre, producto.precio from producto join fabricante on producto.codigo_fabricante = fabricante.codigo and fabricante.nombre like '%e';
use tienda; select producto.nombre, producto.precio from producto join fabricante on producto.codigo_fabricante = fabricante.codigo and fabricante.nombre like '%w%';
use tienda; select nombre, precio, (select nombre from fabricante where producto.codigo_fabricante = fabricante.codigo) as fabricant from producto where precio >= 180 order by precio DESC, nombre ASC;
use tienda; select distinct fabricante.codigo, fabricante.nombre from fabricante join producto on producto.codigo_fabricante = fabricante.codigo; 
use tienda; select fabricante.nombre, producto.nombre from fabricante left join producto on producto.codigo_fabricante = fabricante.codigo; 
use tienda; select fabricante.nombre from fabricante left join producto on producto.codigo_fabricante = fabricante.codigo where producto.nombre is null; 
use tienda; select T.nombre from (select producto.nombre, fabricante.nombre as lenovo from producto left join fabricante on producto.codigo_fabricante = fabricante.codigo and fabricante.nombre = "Lenovo") as T where lenovo is not null;
use tienda; select * from producto where precio = (select precio from (select T.* from (select producto.* , fabricante.nombre as f from producto left join fabricante on producto.codigo_fabricante = fabricante.codigo and fabricante.nombre = "Lenovo") as T where f is not null order by precio desc limit 1)as P);
use tienda; select producto.nombre from producto join fabricante on producto.codigo_fabricante = fabricante.codigo and fabricante.nombre = "Lenovo" order by precio DESC limit 1;
use tienda; select producto.nombre from producto join fabricante on producto.codigo_fabricante = fabricante.codigo and fabricante.nombre = "Hewlett-Packard" order by precio ASC limit 1;
use tienda; select producto.nombre from producto join fabricante on producto.codigo_fabricante = fabricante.codigo where precio > (select avg(precio)from producto join fabricante on producto.codigo_fabricante = fabricante.codigo and fabricante.nombre = "Lenovo");
use tienda; select producto.nombre from producto join fabricante on producto.codigo_fabricante = fabricante.codigo and fabricante.nombre = "Asus" where precio > (select avg(precio)from producto join fabricante on producto.codigo_fabricante = fabricante.codigo and fabricante.nombre = "Asus");
/*Base de dades Universidad*/
use universidad; select apellido1, apellido2, nombre from persona where tipo = "alumno" order by apellido1 desc, apellido2 desc, nombre desc;
use universidad; select apellido1, apellido2, nombre from persona where tipo = "alumno" and telefono is null;
use universidad; select apellido1, apellido2, nombre from persona where tipo = "alumno" and year(fecha_nacimiento) =1999;
use universidad; select apellido1, apellido2, nombre from persona where tipo = "profesor" and telefono is null and nif like '%k';
use universidad; select nombre from asignatura where cuatrimestre = 1 and id_grado = 7 and curso = 3;
use universidad; select persona.apellido1, persona.apellido2, persona.nombre, d.nombre from persona join profesor p on id_profesor = id join departamento d on d.id=p.id_departamento order by apellido1 asc, apellido2 asc, persona.nombre asc;
use universidad; select a.nombre, c.anyo_inicio, anyo_fin from asignatura a join alumno_se_matricula_asignatura aa on a.id = aa.id_asignatura join curso_escolar c on aa.id_curso_escolar =c.id join persona p on p.id =  aa.id_alumno where nif like "26902806M";
use universidad; select distinct nombre from departamento d join profesor p on p.id_departamento = d.id join (select distinct p.id from persona p join asignatura a on a.id_profesor = p.id join grado g on g.id = a.id_grado where p.tipo like "profesor" and g.nombre like 'Grado en Ingenieria Informática (Plan 2015)') as i on i.id = p.id_profesor;
use universidad; select distinct p.nombre, p.apellido1, p.apellido2 from persona p join alumno_se_matricula_asignatura aa on p.id = aa.id_asignatura join curso_escolar c on c.id = aa.id_curso_escolar where c.anyo_inicio = 2018;
/*Resolgui les 6 següents consultes utilitzant les clàusules LEFT JOIN i RIGHT JOIN.*/
/*1*/use universidad; select d.nombre, p.nombre, p.apellido1, p.apellido2 from persona p left join profesor pr on p.id = pr.id_profesor join departamento d on pr.id_departamento= d.id where p.tipo like "profesor";
/*2*/use universidad; select p.nombre, p.apellido1, p.apellido2 from persona p left join profesor pr on p.id = pr.id_profesor join departamento d on pr.id_departamento= d.id where p.tipo like "profesor" and d.nombre is null;
use universidad; select nombre from departamento left join profesor on departamento.id = profesor.id_departamento where profesor.id_departamento is null;
use universidad; select distinct p.nombre, p.apellido1, p.apellido2 from persona p left join asignatura a on p.id = a.id_profesor where p.tipo like "profesor" and a.id_profesor is null;
use universidad; select nombre from asignatura a left join profesor p on a.id_profesor  = p.id_profesor where a.id_profesor is NULL;
use universidad; select distinct d.nombre from departamento d join profesor p on d.id = p.id_departamento join asignatura a on p.id_profesor = a.id_profesor;
/*Consultes resum:*/
use universidad; select count(tipo) from persona where tipo like "alumno";
use universidad; select count(fecha_nacimiento) from persona where year(fecha_nacimiento) = 1999 and tipo like "alumno";
use universidad; select nombre as departament, count(*) from departamento d join profesor p on d.id = p.id_departamento group by p.id_departamento;
/*4*/use universidad; select nombre , count(p.id_departamento) from departamento d left join profesor p on d.id = p.id_departamento group by p.id_departamento;
/*5*/use universidad; select g.nombre , count(a.id_grado) from grado g left join asignatura a on g.id = a.id_grado group by a.id_grado;
use universidad; select g.nombre, count(a.id_grado) as asignaturas from grado g join asignatura a on g.id = a.id_grado group by a.id_grado having count(*) > 40;
use universidad; select distinct g.nombre as grau, a.tipo, sum(a.creditos) from asignatura a join grado g on g.id = a.id_grado group by a.tipo, a.id_grado;
use universidad; select c.anyo_inicio, count(m.id_alumno) as matriculats from curso_escolar c join alumno_se_matricula_asignatura m on c.id = m.id_curso_escolar group by c.anyo_inicio;
/*9*/use universidad; select p.id, p.nombre, p.apellido1, p.apellido2, count(a.nombre) from persona p left join asignatura a on p.id = a.id_profesor where p.tipo like "profesor" group by a.id_profesor;
use universidad; select* from persona where tipo like "alumno" order by fecha_nacimiento desc limit 1;
use universidad; select p.nombre, p.apellido1, p.apellido2, profesor.id_departamento, a.nombre as assignatura from persona p join profesor on p.id = id_profesor left join asignatura a on p.id = a.id_profesor where a.nombre is null;

 